### ISSUE TITLE
error when changing attribute in SBtab

### ISSUE THREAD

**Issue by eladnoor** [tlubitz/SBtab#105]
When I create a table using `from_data_frame`, the `header_row` is created as a list.
However, the code usually assumes it is a string.
This fails in the `change_attribute` function.

Here is some code to reproduce the bug:
```python
import pandas
from sbtab import SBtab
df = pandas.DataFrame(data=[[1, 2], [3, 4]], columns=["x", "y"])
sbtab = SBtab.SBtabTable.from_data_frame(df, table_id="A", table_type="B")
sbtab.change_attribute("attr", 1)
```

**Comment by tlubitz** [comment]
Is there a crucial reason why from_data_frame creates the header as a list? Since SBtab uses a string as header, I would recommend fixing this issue in from_data_frame. I can do that, if you like. Just wanted to ask whether there is a special reasoning behind the list.

**Comment by eladnoor** [comment]
No, it is either a mistake, or some legacy code that I forgot to update.
