### ISSUE TITLE
Hochkomma

### ISSUE THREAD

**Issue by liebermeister** [tlubitz/SBtab#110]
Hi Timo, 

wie schon in der email geschrieben, SBtab scheint bei leeren Tabellenattributen (zB Unit='') das Doppelhochkomma durch ein einzelnes Hochkomma zu ersetzen. Ich könnte mir vorstellen, dass es von den Vorsichtsmaßnahmen für komische nicht-Standard-Anführungszeichen kommt, aber ich konnte das nicht richtig erkennen. Ich hänge ein Testbeispiel an.

Vielen Dank und liebe 
[testfile.tsv.gz](https://github.com/tlubitz/SBtab/files/5704066/testfile.tsv.gz)
[test_unit_attribute.py.gz](https://github.com/tlubitz/SBtab/files/5704068/test_unit_attribute.py.gz)

Grüße
Wolf

**Comment by tlubitz** [comment]
Hi @liebermeister,

zieh Dir mal die neue Version und teste es, bitte. Es sollte jetzt in Ordnung sein.

Liebe Grüße,
Timo
