### ISSUE TITLE
inconsistent line endings being used on windows

### ISSUE THREAD

**Issue by fbergmann** [tlubitz/SBtab#21]
When exporting tsv files on Windows, inconsistent lineendings are being used for the reaction table (a mixture between \r and \r\n this results in the individual reactions to be separated by a new line. it would be nicer for them to be consistent. 

If the csv export has only one type of line endings, so should tsv.

**Comment by timolubitz** [comment]
I tried to "somehow" reproduce it under Ubuntu, but failed. I will take care of this issue as soon as I can get a hold on a Windows/Mac computer. Most probably Macs will have a similiar problem...
