### ISSUE TITLE
python code creates dicts indexed by invented IDs rather than the given IDs

### ISSUE THREAD

**Issue by a-kramer** [tlubitz/SBtab#28]
Hi,
 not sure whether this is on purpose or not, but we ran into an inconvenience where we define valid IDs for each table row (first column, !ID header, unique across all sheets in the document) but in python we have to address things by something else, keys that we did not write, like "Qy1" for _Quantity Tables_. The R code for example does not introduce those Qy[0-9]+ keys... it perfectly imports the columns as we defined them. Is that a known thing?

**Comment by tlubitz** [comment]
Hi,

we are soon rebuilding several parts of SBtab and we will have a close look into your issue during that rebuild. Until then, could you please specify to which part of the code you are referring with "...in python we have to address things by something else, keys that we did not write, like "Qy1" for Quantity Tables...".

Thanks a lot,
Timo
