### ISSUE TITLE
Failing to read SBtabDocument with more than 1 table

### ISSUE THREAD

**Issue by eladnoor** [tlubitz/SBtab#32]
Each table must have a unique filename and "type", otherwise the table is not stored. This is a problem for two reasons:

1. In SBtab.py line 729 this code appears: name_single = filename + '_' + str(i)
    The problem is that later SBtabTable checks the file extension, which is not .tsv anymore.
2. Multiple tables with the same "type" are allowed according to SBtab spec.

**Comment by tlubitz** [comment]
The problem with the filename has been solved by you,
the problem with the multiple tables of the same table_type I just solved.
