### ISSUE TITLE
Date attribute in header_row is causing export issues

### ISSUE THREAD

**Issue by eladnoor** [tlubitz/SBtab#53]
In version 0.9.31, exporting an SBtabTable using return_table_string() contains a bug where the "Date" attribute is printed in a separate line, rather as part of the header row. The function _get_header_row() works properly, but self.header_row is used in the printout function and causes the issue.
A related problem occurs when using _get_custom_table_information() - the string " Date=" is attached to the result.

Also, I would suggest renaming the function return_table_string to something more standard (maybe to_str or as_str).

**Comment by tlubitz** [comment]
Thanks for the feedback. As a matter of fact we are currently dealing with line break issues, involving line breaks introduced as a result of different software tools. These include not only \n, but also ^M and \r line breaks. This might have caused problems, which are partly difficult to reproduce. Thus, I would ask you to update to 0.9.33 and test whether the issue persists. If it does, please send me an exemplary input file that is causing the problem.

**Comment by eladnoor** [comment]
That was fast, I just tested it and the issue is solved in 0.9.33.
