### ISSUE TITLE
More options for I/O of SBtabDocument 

### ISSUE THREAD

**Issue by eladnoor** [tlubitz/SBtab#54]
If I understand it correctly, the SBtabDocument class is meant to be used for files that contain multiple concatenated SBtabTable objects. The write() function works well, but there is no equivalent read() function and right now it seems that I need to add the SBtabTables one by one.
Also, it would be great to have a to_str() function, like the one that exists in the simple SBtabTable class (called return_table_string).

**Comment by tlubitz** [comment]
Thanks!

I changed the SBtabTable.return_table_string() to SBtabTable.to_str(). I agree about this sounding better. Also, I added a to_str() function for the SBtabDocument class.

As for the read function you requested: Currently, it is possible to add multiple concatenated SBtabs via the SBtabDocument.add_sbtab_string(sbtab_string) function. The sbtab_string may contain one or more concatenated SBtabs. Such an sbtab_string can also be employed for the initialisation of the SBtabDocument. Is this what you are asking for?

**Comment by eladnoor** [comment]
I would like to have a single function that creates the SBtabDocument and reads the entire contents from the file (either a filename or a stream). Furthermore, I think standard practice is that a separate function (not the constructor) is used for reading files into a new object. Right now, I need to repeat these 3 lines quite often:
```
with open(file_name, 'r') as sbtab_file:
     file_content = sbtab_file.read()
sbtabdoc = SBtabDocument(file_name, sbtab_init=file_content)
```

Furthermore, the arguments for the SBtabDocument constructor are confusing. I the argument "name" is copied to self.name and to self.filename, while the "filename" argument is used for the add_sbtab_string() function.

**Comment by eladnoor** [comment]
Sorry for not being very clear. I meant that I need to write these 3 lines every time I want to read a new SBtabDocument from a file. I was thinking of just wrapping these 3 lines into one static function (which can also have many optional parameters as well), similar to the pandas.read_csv() function.

**Comment by tlubitz** [comment]
Ah, cool, I get it. Of course, I'll implement it, good idea!

**Comment by tlubitz** [comment]
This is open for testing now. If that's what you needed, please close the issue.

**Comment by eladnoor** [comment]
Great, the read_csv() function works perfectly now. One last thing before I close this issue:
when writing a newly created SBtabDocument to a file, I use the write() function which gets no arguments. Instead, it uses the self.name string as the filename, which is confusing.
I suggest that we have an optional argument called filename (like for SBtabTable.write()), and if it is not provided, the variable self.filename could be used.

**Comment by tlubitz** [comment]
Sounds reasonable. Just did that...
