### ISSUE TITLE
SBtab header is printed incorrectly

### ISSUE THREAD

**Issue by eladnoor** [tlubitz/SBtab#81]
When creating a new SBtab (e.g. from a dataframe), the header row prints empty strings incorrectly (only a single quote, instead of a pair of single quotes). In addition, when changing the "Unit" attribute, the "SBtabVersion" is somehow overridden and the "1.0" appears right after the unit.

To recreate the bug:

```python
from sbtab import SBtab
import pandas as pd

df = pd.DataFrame([["glucose", 121.4], ["galactose", 141.7]],
                  columns=["compound_name", "dG0_prime"])

sbtab = SBtab.SBtabTable.from_data_frame(
    df, table_id="Compound",
    table_type="Compound")

sbtab.change_attribute("Unit", "kJ/mol")
print(sbtab.to_str())
```
the result is:
```
!!SBtab TableID='Compound' TableType='Compound' TableName='Compound' DocumentName=' Document=' Unit='kJ/mol'1.0' Date='2019-11-27'
!compound_name	!dG0_prime
glucose	121.4
galactose	141.7
```

**Comment by eladnoor** [comment]
Thanks. Would you mind making a new pypi version with this patched?

**Comment by tlubitz** [comment]
I'll do that! But only next week, as I am close to being out of office today.
Have a nice weekend,
Timo

**Comment by tlubitz** [comment]
Okay, I updated the installer. Closing this for now...
