### ISSUE TITLE
Support for TableType 'Config'

### ISSUE THREAD

**Issue by eladnoor** [tlubitz/SBtab#88]
Hi Timo,

It seems that the latest version on PyPI is slightly behind (0.9.72, released December 1st) and that a change was made to the `definitions.tsv` file on December 2nd for adding "Config".
I guess that a new PyPI release would solve the issue.

**Comment by tlubitz** [comment]
Thanks, Elad, I'll take care of it this week I hope

**Comment by tlubitz** [comment]
That should be sorted out.

Cheers
