### ISSUE TITLE
"AttributeError: module 'misc' has no attribute 'getDelimiter'"

### ISSUE THREAD

**Issue by liebermeister** [tlubitz/SBtab#89]
Hi Timo,

ich hab gerade den Validator in der Kommandozeile verwenden wollen und bekomme den Fehler:

Traceback (most recent call last):
  File "/home/wolfram/projekte/sbtab/github/SBtab/python/validatorSBtab.py", line 341, in <module>
    delimiter = misc.getDelimiter(sbtab_file)
AttributeError: module 'misc' has no attribute 'getDelimiter'

Kannst Du damit was anfangen?

LG Wolf

**Comment by tlubitz** [comment]
removed deprecated main function;

**Comment by liebermeister** [comment]
Danke! Jetzt bekomme ich den Fehler:

Traceback (most recent call last):
  File
"/home/wolfram/projekte/sbtab/github/SBtab/python/sbtab_validator.py", line
46, in validator_wrapper
    sbtab = SBtab.SBtabTable(f, args.sbtab)
  File "/home/wolfram/projekte/sbtab/github/SBtab/python/SBtab.py", line
88, in __init__
    self._singular()
  File "/home/wolfram/projekte/sbtab/github/SBtab/python/SBtab.py", line
125, in _singular
    raise SBtabError('There are more than one SBtab tables in this file.
Please'\
SBtab.SBtabError: There are more than one SBtab tables in this file. Please
use the SBtabDocument class instead of SBtabTable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File
"/home/wolfram/projekte/sbtab/github/SBtab/python/sbtab_validator.py", line
89, in <module>
    validator_wrapper(args)
  File
"/home/wolfram/projekte/sbtab/github/SBtab/python/sbtab_validator.py", line
48, in validator_wrapper
    raise SBtabError('SBtab Table %s could not be created.' % args.sbtab)
__main__.SBtabError: SBtab Table
./ecoli_noor_2016/ecoli_noor_2016_ECM_Model.tsv could not be created.

Kann es sein, dass man nur einzelne Tabellen validieren kann und nicht
Dateien, die ein ganzes SBtab-Dokument enthalten?

LG Wolf

**Comment by tlubitz** [comment]
Hi Wolf,

für Dokumente muss man die Flag -d verwenden.
Falls das nicht gehen sollte, schick mir bitte mal die Datei zum Testen.

Liebe Grüße,
Timo

Am Mo., 13. Juli 2020 um 19:21 Uhr schrieb Wolfram Liebermeister <
notifications@github.com>:

**Comment by liebermeister** [comment]
Danke!!

Im Hilfetext von sbtab_validator.py, kannst Du noch "create" durch
"validate" ersetzen?
Und wäre es leicht zu machen, dass das Kommandozeilenprogramm automatisch
erkennt, ob es sich bei der Eingabedatei um eine Tabelle oder ein Dokument
handelt? Und für die Ausgabe, könntest Du anstatt der python-Liste die
Meldungen einfach Zeile für Zeile als Strings ausgeben?
(Bitte beides nicht programmieren, sondern auf die Liste setzen, es sei
denn es sind absolute Kleinigkeiten für Dich).

**Comment by tlubitz** [comment]
Create habe ich durch Validate ersetzt, die Ausgabe habe ich jetzt Zeile für Zeile anstelle von von der Python-Liste.

Die automatische Erkennung von Table/Document wäre etwas komplexer, das habe ich auf die Liste gesetzt

**Comment by liebermeister** [comment]
Danke!

Hättest Du in den nächsten Tagen Zeit zu reden? Oder lieber nächste Woche?

Viele Grüße
Wolf

**Comment by tlubitz** [comment]
Bei mir sind diese Woche die Vormittage ziemlich voll, aber so ab 13 Uhr kann ich eigentlich immer (bis maximal 16 Uhr). Heute ginge es auch...
