### ISSUE TITLE
Fehlender Zeilenumbruch

### ISSUE THREAD

**Issue by liebermeister** [tlubitz/SBtab#93]
Hallo Timo,

Oliver Bodeit schreibt mit Hilfe des SBtab-Pakets SBtab-Dateien raus, und es fehlt der Zeilenumbruch zwischen der "!!!.."-Zeile und der "!!.."_Zeile. Weißt Du von dem Problem? Falls nicht, könntest Du Dich mit Oliver in Verbindung setzen, damit er Dir die Umstände erklärt bzw ein Beispiel gibt?

Vielen Dank!

Liebe Grüße
Wolf

**Comment by tlubitz** [comment]
Hi Wolf,

das Problem bei Oliver hatten wir schon öfter und es konnte mir nie jemand
ein Szenario geben, in dem das auftritt, darum konnte ich den Fehler nie
reproduzieren und dementsprechend nie fixen. Ich werds morgen nochmal mit
Oliver versuchen.

Liebe Grüße,
Timo

Am Mo., 12. Okt. 2020 um 16:37 Uhr schrieb Wolfram Liebermeister <
notifications@github.com>:

**Comment by liebermeister** [comment]
Danke!!

Wolf
