### ISSUE TITLE
sbml2sbtab.py cannot find SBtab library (and how to use it)

### ISSUE THREAD

**Issue by smoretti** [tlubitz/SBtab#94]
Hi

I am testing _sbml2sbtab.py_ from https://github.com/tlubitz/SBtab/blob/master/python/sbml2sbtab.py
I installed sbtab with the archive from pip and I had to change `except: import SBtab` into `except: import sbtab` to make it work without error at load time.

Also now I wonder how to use it?
`python3 sbml2sbtab.py --filename=bigg_e_coli_core.sbml`  does not convert anything.

Thanks

**Comment by tlubitz** [comment]
Hi!

The command line tool you are searching for is called sbtab_sbml2sbtab.py,
not sbml2sbtab.py

Please see the instructions on the usage in the folder /SBtab/python/ on
GitHub.

Let me know if any problems arise.

Best
Timo

**Comment by smoretti** [comment]
I use the right script now, **sbtab_sbml2sbtab.py**, thanks.
In the same directory I have also added _SBtab.py_, _misc.py_ and _sbml2sbtab.py_.

Nevertheless the conversion failed on my test SBML file:
`['Could not generate SBtab Compartment.', 'Could not generate SBtab Compound.', 'Could not generate SBtab Reaction.', 'Could not generate SBtab Quantity.', 'Could not generate SBtab FBC Objective Function.', 'Could not generate SBtab FBC Gene.']`

My SBML test file is the SBML from http://bigg.ucsd.edu/models/e_coli_core
`python3 sbtab_sbml2sbtab.py e_coli_core.xml`


Python 3.5.2
libsbml 5.18.0
openpyxl 2.5.4
numpy 1.16.2
scipy 1.2.1
CentOS Linux 7.6.1810

**Comment by tlubitz** [comment]
That is a bit odd... I was trying the exact same thing with the
e_coli_core.xml (as attached) and it worked well when doing

python3 sbtab_sbml2sbtab.py e_coli_core.xml

Did you make any alterations on the SBML model? Do you have all files in
the directory that are also present in the /SBtab/python/ directory? Please
also make sure to provide the definitions.tsv, which you can find in the
repository /SBtab/definition_table/definitions.tsv. You can basically just
c&p it in the directory where you are running your sbtab_sbml2sbtab script
(and where the other modules are located).

Let me know if this helped. Until then I am sending you the output that I
produced from the ecoli model.




Am Fr., 16. Okt. 2020 um 08:38 Uhr schrieb smoretti <
notifications@github.com>:

**Comment by smoretti** [comment]
Thanks it works now.
I missed the _/SBtab/definition_table/definitions.tsv_ file.

What is the difference between _sbtab.tsv_ and _objtables.tsv_ files?

**Comment by tlubitz** [comment]
Super, glad to hear it. I assumed it might have been the missing
definitions file, but it was missing a more sensible error code.

The difference between sbtab.tsv and objtables.tsv is simply two different
standard formats. We are mainly working with SBtab, which is specified on
the website sbtab.net. Just recently we also built in the slightly
different syntax of objtables, which is specified on objtables.org. The two
are pretty similar, and the content is the same. I didn't know which one
you needed so I simply sent both.



Am Fr., 16. Okt. 2020 um 11:00 Uhr schrieb smoretti <
notifications@github.com>:

**Comment by smoretti** [comment]
I was not aware of objtables.org
Thanks again
