### ISSUE TITLE
SBML2SBtab converter

### ISSUE THREAD

**Issue by liebermeister** [tlubitz/SBtab#95]
Hi Timo,

I tried to convert the hynne.xml example file (from the Sbtab repo) to SBtab. Both the commandline converter and the online converter throw error messages. The SBML file seems to be valid (according to the online SBML validator). Can you check this?

Thank you!

Best, Wolf

**Comment by tlubitz** [comment]
Hi Wolf,

I could reproduce the problem with the online converter.

I could NOT reproduce it with the current version of the commandline
converter sbtab_sbml2sbtab.py. Could you check whether you have the most
current version and report back whether the problem persists?

I'll update the online converter soon, it's a bit behind in versioning.

Best
Timo


Am So., 18. Okt. 2020 um 20:06 Uhr schrieb Wolfram Liebermeister <
notifications@github.com>:

**Comment by tlubitz** [comment]
Hi Wolf^2

the online converter should work fine again.

Please still report back because of the commandline converter..

Best
Timo

**Comment by liebermeister** [comment]
Hallo Timo,

Vielen Dank!

Hier ist die Fehlermeldung vom Kommandozeilen-Konverter, vielleicht kannst
Du Dir einen Reim drauf machen?

Danke!

wolfram@persephone|/tmp:python3
/home/wolfram/projekte/sbtab/github/SBtab/python/sbtab_sbtab2sbml.py
/home/wolfram/projekte/sbtab/github/SBtab/sbtab_examples/hynne/hynne.xml
Traceback (most recent call last):
  File "/home/wolfram/projekte/sbtab/github/SBtab/python/SBtab.py", line
1059, in add_sbtab_string
    sbtab = SBtabTable(sbtab_string, filename)
  File "/home/wolfram/projekte/sbtab/github/SBtab/python/SBtab.py", line
85, in __init__
    self.add_sbtab_string(table_string)
  File "/home/wolfram/projekte/sbtab/github/SBtab/python/SBtab.py", line
547, in add_sbtab_string
    self.table = self._cut_table_string(self.preprocess)
  File "/home/wolfram/projekte/sbtab/github/SBtab/python/SBtab.py", line
146, in _cut_table_string
    if row.replace(delimiter, '') != '' and row.replace(delimiter, '') !=
'[]':
TypeError: replace() argument 1 must be str, not bool

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File
"/home/wolfram/projekte/sbtab/github/SBtab/python/sbtab_sbtab2sbml.py",
line 40, in converter_sbtab2sbml_wrapper
    sbtab_doc = SBtab.SBtabDocument('conversion_document', f, args.sbtab)
  File "/home/wolfram/projekte/sbtab/github/SBtab/python/SBtab.py", line
968, in __init__
    self.add_sbtab_string(sbtab_init, filename)
  File "/home/wolfram/projekte/sbtab/github/SBtab/python/SBtab.py", line
1063, in add_sbtab_string
    'ated properly: ' + str(e))
SBtab.SBtabError: The SBtab Table object could not be created properly:
replace() argument 1 must be str, not bool

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File
"/home/wolfram/projekte/sbtab/github/SBtab/python/sbtab_sbtab2sbml.py",
line 78, in <module>
    converter_sbtab2sbml_wrapper(args)
  File
"/home/wolfram/projekte/sbtab/github/SBtab/python/sbtab_sbtab2sbml.py",
line 42, in converter_sbtab2sbml_wrapper
    raise SBtabError('SBtab Document %s could not be created.' % args.sbtab)
__main__.SBtabError: SBtab Document
/home/wolfram/projekte/sbtab/github/SBtab/sbtab_examples/hynne/hynne.xml
could not be created.

**Comment by tlubitz** [comment]
Hi Wolf,

nur ganz kurz:

Du benutzt das Skript sbtab_sbtab2sbml.py, aber Du übergibst ein
SBML-Modell. Du benötigst das Skript sbtab_sbml2sbtab.py

Schau mal, ob das das Problem eventuell schon behebt.

Liebe Grüße,
Timo

Am Mo., 19. Okt. 2020 um 20:09 Uhr schrieb Wolfram Liebermeister <
notifications@github.com>:

**Comment by liebermeister** [comment]
Au weia, da hatte ich ja Tomaten auf den Augen!!

Vielen Dank für Deine Hilfe .. und sorry ... !

Liebe Grüße
Wolf
